{{- if eq .Cluster.ConfigItems.enable_csi_migration "true" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ebs-csi-controller
  namespace: kube-system
  labels:
    application: kubernetes
    component: ebs-csi-controller
spec:
  selector:
    matchLabels:
      daemonset: ebs-csi-controller
  template:
    metadata:
      labels:
        application: kubernetes
        component: ebs-csi-controller
        daemonset: ebs-csi-controller
      annotations:
        logging/destination: "{{.Cluster.ConfigItems.log_destination_infra}}"
    spec:
      containers:
        - args:
            - controller
            - --endpoint=$(CSI_ENDPOINT)
            - --logtostderr
            - --v=5
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
          image: registry.opensource.zalan.do/teapot/ebs-csi-driver:v0.5.0-master-2
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          name: ebs-plugin
          ports:
            - containerPort: 9808
              name: healthz
              protocol: TCP
          resources:
            requests:
              cpu: 25m
              memory: 50Mi
            limits:
              cpu: 25m
              memory: 50Mi
          volumeMounts:
            - mountPath: /var/lib/csi/sockets/pluginproxy/
              name: socket-dir
        - args:
            - --csi-address=$(ADDRESS)
            - --v=5
            - --feature-gates=Topology=true
            - --enable-leader-election
            - --leader-election-type=leases
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          image: registry.opensource.zalan.do/teapot/csi-provisioner:v1.6.0-master-4
          name: csi-provisioner
          resources:
            requests:
              cpu: 25m
              memory: 50Mi
            limits:
              cpu: 25m
              memory: 50Mi
          volumeMounts:
            - mountPath: /var/lib/csi/sockets/pluginproxy/
              name: socket-dir
        - args:
            - --csi-address=$(ADDRESS)
            - --v=5
            - --leader-election=true
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          image: registry.opensource.zalan.do/teapot/csi-attacher:v2.2.0-master-4
          name: csi-attacher
          resources:
            requests:
              cpu: 25m
              memory: 50Mi
            limits:
              cpu: 25m
              memory: 50Mi
          volumeMounts:
            - mountPath: /var/lib/csi/sockets/pluginproxy/
              name: socket-dir
        - args:
            - --csi-address=/csi/csi.sock
          image: registry.opensource.zalan.do/teapot/livenessprobe:v2.0.0-master-4
          name: liveness-probe
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - name: csi-resizer
          image: registry.opensource.zalan.do/teapot/csi-resizer:v0.5.0-master-4
          args:
            - --csi-address=$(ADDRESS)
            - --v=5
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          resources:
            requests:
              cpu: 25m
              memory: 50Mi
            limits:
              cpu: 25m
              memory: 50Mi
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
      nodeSelector:
        node.kubernetes.io/role: master
      serviceAccountName: ebs-csi-controller
      tolerations:
        - key: node.kubernetes.io/role
          value: master
          effect: NoSchedule
      volumes:
        - emptyDir: {}
          name: socket-dir
{{- end }}
