apiVersion: v1
kind: Service
metadata:
  name: kube-metrics-adapter
  namespace: kube-system
spec:
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
  selector:
    application: kubernetes
    component: metrics-adapter
