apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-aws-iam-controller
  namespace: kube-system
  labels:
    application: kubernetes
    component: aws-iam-controller
    version: v0.1.2
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: kube-aws-iam-controller
  template:
    metadata:
      labels:
        application: kubernetes
        component: aws-iam-controller
        deployment: kube-aws-iam-controller
        version: v0.1.2
      annotations:
        logging/destination: "{{.Cluster.ConfigItems.log_destination_infra}}"
    spec:
      serviceAccountName: kube-aws-iam-controller
      priorityClassName: "{{ .Cluster.ConfigItems.system_priority_class }}"
      # running with hostNetwork to bypass metadata service block from pod
      # network.
      hostNetwork: true
      containers:
      - name: kube-aws-iam-controller
        image: registry.opensource.zalan.do/teapot/kube-aws-iam-controller:v0.1.2
        args:
        - --debug
        - "--assume-role={{.Cluster.LocalID}}-worker"
        resources:
          limits:
            cpu: "{{.ConfigItems.kube_aws_iam_controller_cpu}}"
            memory: "{{.ConfigItems.kube_aws_iam_controller_mem_max}}"
          requests:
            cpu: "{{.ConfigItems.kube_aws_iam_controller_cpu}}"
            memory: "{{.ConfigItems.kube_aws_iam_controller_mem_max}}"
      tolerations:
      - key: node.kubernetes.io/role
        value: master
        effect: NoSchedule
      nodeSelector:
        node.kubernetes.io/role: master
