apiVersion: "zalando.org/v1"
kind: PlatformCredentialsSet
metadata:
  name: admission-controller-credentials
  namespace: kube-system
  labels:
    application: kubernetes
    component: kube-apiserver
spec:
  application: kubernetes
  tokens:
    kio:
      privileges: []
    docker-meta:
      privileges: []
