apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  namespace: kube-system
  annotations:
    zalando.org/skipper-filter: |
      oauthTokeninfoAnyKV("realm", "/employees", "realm", "/services")
  labels:
    application: prometheus
spec:
  rules:
  - host: system-prometheus.{{ .Values.hosted_zone }}
    http:
      paths:
      - backend:
          service:
            name: prometheus
            port:
              number: 80
        pathType: ImplementationSpecific
