apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdb-controller
  namespace: kube-system
  labels:
    application: kubernetes
    component: pdb-controller
    version: v0.0.17
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: pdb-controller
  template:
    metadata:
      labels:
        deployment: pdb-controller
        application: kubernetes
        component: pdb-controller
        version: v0.0.17
      annotations:
        logging/destination: "{{.Cluster.ConfigItems.log_destination_infra}}"
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      serviceAccountName: pdb-controller
      containers:
      - name: pdb-controller
        image: registry.opensource.zalan.do/teapot/pdb-controller:v0.0.17
        args:
          - --debug
{{- if ne .Cluster.ConfigItems.pdb_controller_non_ready_ttl "" }}
          - --non-ready-ttl={{.Cluster.ConfigItems.pdb_controller_non_ready_ttl}}
{{- end }}
{{- if eq .Cluster.ConfigItems.teapot_admission_controller_parent_resource_hash "true" }}
          - --use-parent-resource-hash
{{- end }}
          - "--max-unavailable={{.Cluster.ConfigItems.pdb_controller_max_unavailable}}"
        resources:
          limits:
            cpu: 10m
            memory: 4Gi
          requests:
            cpu: 10m
            memory: 4Gi
