apiVersion: zalando.org/v1
kind: PlatformCredentialsSet
metadata:
  name: "deployment-service-controller-credentials"
  namespace: "kube-system"
  labels:
    application: "deployment-service"
    component: "controller"
spec:
  application: "deployment-service"
  tokens:
    status-service:
      kind: KubernetesAPILocal
      privileges: []
