apiVersion: v1
kind: Service
metadata:
  name: "deployment-service-controller"
  namespace: "kube-system"
  labels:
    application: "deployment-service"
    component: "controller"
spec:
  type: ClusterIP
  selector:
    application: "deployment-service"
    component: "controller"
  clusterIP: None
