apiVersion: v1
kind: Service
metadata:
  name: "deployment-service-status-service"
  namespace: "kube-system"
  labels:
    application: "deployment-service"
    component: "status-service"
spec:
  type: ClusterIP
  selector:
    application: "deployment-service"
    component: "status-service"
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
