apiVersion: v1
kind: Secret
metadata:
  name: vpa-tls-certs
  namespace: kube-system
  labels:
    application: vertical-pod-autoscaler
    component: admission-controller
type: Opaque
data:
  caKey.pem: ""
  caCert.pem: "{{ .ConfigItems.ca_cert_decompressed }}"
  serverCert.pem: "{{ .ConfigItems.vpa_webhook_cert }}"
  serverKey.pem: "{{ .ConfigItems.vpa_webhook_key }}"
