apiVersion: v1
kind: Service
metadata:
  name: vpa-webhook
  namespace: kube-system
  labels:
    application: vertical-pod-autoscaler
    component: admission-controller
    version: master
spec:
  selector:
    application: vertical-pod-autoscaler
    component: admission-controller
  ports:
    - port: 443
      targetPort: 8000
      protocol: TCP
