{{ $version := "v0.0.5" }}

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-node-ready
  namespace: kube-system
  labels:
    application: kubernetes
    component: kube-node-ready
    version: {{$version}}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      daemonset: kube-node-ready
  template:
    metadata:
      labels:
        daemonset: kube-node-ready
        application: kubernetes
        component: kube-node-ready
        version: {{$version}}
      annotations:
        logging/destination: "{{.Cluster.ConfigItems.log_destination_infra}}"
    spec:
      serviceAccountName: kube-node-ready
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      priorityClassName: system-node-critical
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      containers:
      - name: kube-node-ready
        image: registry.opensource.zalan.do/teapot/kube-node-ready:{{$version}}
        args:
        - --lifecycle-hook=kube-node-ready-lifecycle-hook
        resources:
          requests:
            cpu: 1m
            memory: 50Mi
            ephemeral-storage: 256Mi
          limits:
            cpu: 1m
            memory: 50Mi
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 300
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
      securityContext:
        fsGroup: 65534
