{{ if ne .Cluster.ConfigItems.audittrail_url "" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: audittrail-adapter
  namespace: kube-system
  labels:
    application: audittrail-adapter
    version: master-26
spec:
  selector:
    matchLabels:
      application: audittrail-adapter
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        application: audittrail-adapter
        version: master-26
      annotations:
        logging/destination: "{{.Cluster.ConfigItems.log_destination_infra}}"
        prometheus.io/path: /metrics
        prometheus.io/port: "7980"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: audittrail-adapter
      priorityClassName: system-node-critical
      nodeSelector:
        node.kubernetes.io/role: master
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      hostNetwork: true
      containers:
      - name: audittrail-adapter
        image: pierone.stups.zalan.do/teapot/audittrail-adapter:master-26
        env:
          - name: AWS_REGION
            value: {{.Cluster.Region}}
        args:
        - --cluster-id={{ .ID }}
        - --audittrail-url={{.Cluster.ConfigItems.audittrail_url}}
        - --s3-bucket-name=zalando-audittrail-{{accountID .InfrastructureAccount}}-{{.LocalID}}
        - --address=:8889
        - --metrics-address=:7980
        volumeMounts:
        - name: platform-iam-credentials
          mountPath: /meta/credentials
          readOnly: true
        resources:
          limits:
            cpu: 50m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 200Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
      volumes:
      - name: platform-iam-credentials
        secret:
          secretName: audittrail-adapter
{{ end }}
